### ISSUE TITLE
Extract addresses from Script

### ISSUE THREAD

**Issue by alexbirkett** [apoelstra/rust-bitcoin#27]
How do I extract the addresses from a `Script`?

I can only find an example of putting an address into a `Script`:

```
fn script_builder() {
        // from txid 3bb5e6434c11fb93f64574af5d116736510717f2c595eb45b52c28e31622dfff which was in my mempool when I wrote the test
        let script = Builder::new().push_opcode(opcodes::All::OP_DUP)
                                   .push_opcode(opcodes::All::OP_HASH160)
                                   .push_slice(&"16e1ae70ff0fa102905d4af297f6912bda6cce19".from_hex().unwrap())
                                   .push_opcode(opcodes::All::OP_EQUALVERIFY)
                                   .push_opcode(opcodes::All::OP_CHECKSIG)
                                   .into_script();
        assert_eq!(&format!("{:x}", script), "76a91416e1ae70ff0fa102905d4af297f6912bda6cce1988ac");
    }
 ```

**Comment by apoelstra** [comment]
There is no API function to do it right now, you just have template-match, extract the hash and build an [address struct](https://www.wpsoftware.net/rustdoc/bitcoin/util/address/struct.Address.html) manually.

**Comment by kyluke** [comment]
Any update on this? I've been reading through the code since yesterday and only find https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/address.rs#L139 and this https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/address.rs#L97 really to go from a script to an address.

I see the other conversions go from PubKey to addresses, but if you deserialize a transaction, the outputs are scripts. Is there any easy way here to go from a script to any of the other address types? Or at least, from a script to a pub key? I haven't found anything related to that yet.

**Comment by stevenroose** [comment]
@apoelstra I suppose eventually script descriptors will land in rust-bitcoin? Any idea when/how? I could look into porting descriptor code from rust-miniscript so that rust-miniscript just has the compiler code.

**Comment by apoelstra** [comment]
@stevenroose my original thought was that we'd keep descriptors separate from rust-bitcoin, and wallet implementors would need both libraries. The reason being that Miniscript de/serialization is a pretty big chunk of code which is needed to make descriptors useful for us.

On the other hand, we may find that we want tight coupling between PSBT and output descriptors; unsure; in which case we'd need descriptor types in rust-bitcoin.

Do you have a specific idea for how this would look?

**Comment by stevenroose** [comment]
> Do you have a specific idea for how this would look?

Do you mean how the descriptor API/functionality would look without having conversion with `Script` (compilation and decompilation)?

I just reasoned that descriptors are a quite passive this just like `Address`. I guess I would only do to and from string conversion (so just the syntax). And refer to miniscript for compilation and decompilation to the `Script` type.

I realize it might be a bit strange to have to refer to an external crate for the most fundamental part of the descriptor concept :D Possibly we could have a compilation target `miniscript` that introduces `TryTo<Script>` and `TryFrom<Script>` using a miniscript dependency. That would make a circular dependency, though.

One argument for having just the passive type here would be that in the near future, we might see descriptors in a lot of APIs as an alternative to addresses. So even just for JSON and text serialization it would be nice to have so that packages don't need to have the miniscript dependency.
